<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="0" total="1" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="NegativeTestSuite" duration-ms="15413" started-at="2019-02-11T05:48:49Z" finished-at="2019-02-11T05:49:05Z">
    <groups>
    </groups>
    <test name="ExceptionTest" duration-ms="15413" started-at="2019-02-11T05:48:49Z" finished-at="2019-02-11T05:49:05Z">
      <class name="com.logili.tv.ExceptionDemo">
        <test-method status="PASS" signature="logInTest()[pri:0, instance:com.logili.tv.ExceptionDemo@56cdfb3b]" name="logInTest" duration-ms="14710" started-at="2019-02-11T05:48:49Z" finished-at="2019-02-11T05:49:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logInTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.logili.tv.ExceptionDemo@56cdfb3b]" name="tearDown" is-config="true" duration-ms="687" started-at="2019-02-11T05:49:04Z" finished-at="2019-02-11T05:49:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.logili.tv.ExceptionDemo -->
    </test> <!-- ExceptionTest -->
  </suite> <!-- NegativeTestSuite -->
</testng-results>
